package projetoTest;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import excecoes.ValidacaoException;
import projeto.Date;
import projeto.Monitoria;

public class MonitoriaTest {
	private Monitoria ext;
	
	@Before
	public void setUp() throws Exception {
		ext = new Monitoria("Monitoria de lp2","auxiliar","01/01/2017",12,"lp2","2016.2",95);
	}

	@Test
	public void construtorTest() throws ValidacaoException {
		assertEquals("Monitoria de lp2", ext.getNome());
		assertEquals("auxiliar", ext.getObjetivo());
		assertEquals(new Date("01/01/2017"),ext.getDataInicio());
		assertEquals(12,ext.getDuracao());
		assertEquals(95,ext.getRendimento());
	}
	
	@Test
	public void construtorWithFailTest() {
		try {
			new Monitoria("    ","auxiliar","01/01/2017",12,"lp2","2016.2",95);
			fail();
		}
		catch(ValidacaoException e) {
			assertEquals("Nome de projeto nao pode ser nulo ou vazio",e.getMessage());
		}
		
		try {
			new Monitoria("Monitoria de lp2","auxiliar","01/01/2017",12,"lp2","2016.2",105);
			fail();
		}
		catch(ValidacaoException e) {
			assertEquals("Rendimento precisa estar entre 0 e 100",e.getMessage());
		}
	}
}