package pessoaTest;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import excecoes.ValidacaoException;
import pessoa.*;

public class PessoaControllerTest {
	PessoaController pessoas;
	
	@Before
	public void setUp() throws Exception {
		pessoas = new PessoaController();
		pessoas.cadastraPessoa("222.333.444-55","Natasha","natasha@ccc.ufcg.edu.br");
	}
	
	@Test
	public void removePessoaTest() throws ValidacaoException {
		try {
			pessoas.removePessoa("222.333.444-50");
			fail();
		}
		catch(Exception e) {
			assertEquals("Erro na consulta de pessoa: Pessoa nao encontrada",e.getMessage());
		}
		try {
			pessoas.removePessoa("222.333.444-55");
		}
		catch(Exception e) {
			fail();
		}
	}
	
	@Test
	public void recuperaPessoaTest() {
		Pessoa pessoinha = pessoas.recuperaPessoa("222.333.444-55");
		assertEquals("Natasha",pessoinha.getNome());
	}

	@Test
	public void toStringTest() throws ValidacaoException {
		final String FIM_DE_LINHA = System.lineSeparator();
		assertEquals("Cpf: 222.333.444-55"
				   + FIM_DE_LINHA
				   + "Nome: Natasha"
				   + FIM_DE_LINHA
				   + "Email: natasha@ccc.ufcg.edu.br"
				   + FIM_DE_LINHA
				   ,pessoas.toString());
	}
}
